var _ignore_interaction_helper_8cs =
[
    [ "AerodynamicObjects.Utility.IgnoreInteractionHelper", "class_aerodynamic_objects_1_1_utility_1_1_ignore_interaction_helper.html", "class_aerodynamic_objects_1_1_utility_1_1_ignore_interaction_helper" ],
    [ "AerodynamicObjects.Utility.IgnoreInteractionHelper.IgnoreInteractionCollection", "class_aerodynamic_objects_1_1_utility_1_1_ignore_interaction_helper_1_1_ignore_interaction_collection.html", "class_aerodynamic_objects_1_1_utility_1_1_ignore_interaction_helper_1_1_ignore_interaction_collection" ]
];