var annotated_dup =
[
    [ "AerodynamicObjects", "namespace_aerodynamic_objects.html", [
      [ "Aerodynamics", "namespace_aerodynamic_objects_1_1_aerodynamics.html", [
        [ "AdvancedBuoyancyModel", "class_aerodynamic_objects_1_1_aerodynamics_1_1_advanced_buoyancy_model.html", "class_aerodynamic_objects_1_1_aerodynamics_1_1_advanced_buoyancy_model" ],
        [ "BuoyancyModel", "class_aerodynamic_objects_1_1_aerodynamics_1_1_buoyancy_model.html", "class_aerodynamic_objects_1_1_aerodynamics_1_1_buoyancy_model" ],
        [ "DragModel", "class_aerodynamic_objects_1_1_aerodynamics_1_1_drag_model.html", "class_aerodynamic_objects_1_1_aerodynamics_1_1_drag_model" ],
        [ "IAerodynamicModel", "interface_aerodynamic_objects_1_1_aerodynamics_1_1_i_aerodynamic_model.html", "interface_aerodynamic_objects_1_1_aerodynamics_1_1_i_aerodynamic_model" ],
        [ "LiftModel", "class_aerodynamic_objects_1_1_aerodynamics_1_1_lift_model.html", "class_aerodynamic_objects_1_1_aerodynamics_1_1_lift_model" ],
        [ "RotationalDampingModel", "class_aerodynamic_objects_1_1_aerodynamics_1_1_rotational_damping_model.html", "class_aerodynamic_objects_1_1_aerodynamics_1_1_rotational_damping_model" ],
        [ "RotationalLiftModel", "class_aerodynamic_objects_1_1_aerodynamics_1_1_rotational_lift_model.html", "class_aerodynamic_objects_1_1_aerodynamics_1_1_rotational_lift_model" ],
        [ "UserSuppliedDragModel", "class_aerodynamic_objects_1_1_aerodynamics_1_1_user_supplied_drag_model.html", "class_aerodynamic_objects_1_1_aerodynamics_1_1_user_supplied_drag_model" ]
      ] ],
      [ "Control", "namespace_aerodynamic_objects_1_1_control.html", [
        [ "Actuator", "class_aerodynamic_objects_1_1_control_1_1_actuator.html", "class_aerodynamic_objects_1_1_control_1_1_actuator" ],
        [ "PIDController", "class_aerodynamic_objects_1_1_control_1_1_p_i_d_controller.html", "class_aerodynamic_objects_1_1_control_1_1_p_i_d_controller" ],
        [ "PIDDrawer", "class_aerodynamic_objects_1_1_control_1_1_p_i_d_drawer.html", "class_aerodynamic_objects_1_1_control_1_1_p_i_d_drawer" ],
        [ "SimpleThrustArrow", "class_aerodynamic_objects_1_1_control_1_1_simple_thrust_arrow.html", "class_aerodynamic_objects_1_1_control_1_1_simple_thrust_arrow" ],
        [ "SimpleThruster", "class_aerodynamic_objects_1_1_control_1_1_simple_thruster.html", "class_aerodynamic_objects_1_1_control_1_1_simple_thruster" ]
      ] ],
      [ "Demos", "namespace_aerodynamic_objects_1_1_demos.html", [
        [ "AeroObjectSpawner", "class_aerodynamic_objects_1_1_demos_1_1_aero_object_spawner.html", "class_aerodynamic_objects_1_1_demos_1_1_aero_object_spawner" ],
        [ "Airship", "class_aerodynamic_objects_1_1_demos_1_1_airship.html", "class_aerodynamic_objects_1_1_demos_1_1_airship" ],
        [ "AirshipEditor", "class_aerodynamic_objects_1_1_demos_1_1_airship_editor.html", "class_aerodynamic_objects_1_1_demos_1_1_airship_editor" ],
        [ "AlignWithFlow", "class_aerodynamic_objects_1_1_demos_1_1_align_with_flow.html", "class_aerodynamic_objects_1_1_demos_1_1_align_with_flow" ],
        [ "AnemometerSpeedLogger", "class_aerodynamic_objects_1_1_demos_1_1_anemometer_speed_logger.html", "class_aerodynamic_objects_1_1_demos_1_1_anemometer_speed_logger" ],
        [ "AngularVelocityWarning", "class_aerodynamic_objects_1_1_demos_1_1_angular_velocity_warning.html", null ],
        [ "BalloonController", "class_aerodynamic_objects_1_1_demos_1_1_balloon_controller.html", "class_aerodynamic_objects_1_1_demos_1_1_balloon_controller" ],
        [ "BalloonControllerEditor", "class_aerodynamic_objects_1_1_demos_1_1_balloon_controller_editor.html", "class_aerodynamic_objects_1_1_demos_1_1_balloon_controller_editor" ],
        [ "BalloonString", "class_aerodynamic_objects_1_1_demos_1_1_balloon_string.html", "class_aerodynamic_objects_1_1_demos_1_1_balloon_string" ],
        [ "BaseAircraftController", "class_aerodynamic_objects_1_1_demos_1_1_base_aircraft_controller.html", "class_aerodynamic_objects_1_1_demos_1_1_base_aircraft_controller" ],
        [ "BodyMotion", "class_aerodynamic_objects_1_1_demos_1_1_body_motion.html", "class_aerodynamic_objects_1_1_demos_1_1_body_motion" ],
        [ "CameraBillboard", "class_aerodynamic_objects_1_1_demos_1_1_camera_billboard.html", null ],
        [ "CameraManager", "class_aerodynamic_objects_1_1_demos_1_1_camera_manager.html", "class_aerodynamic_objects_1_1_demos_1_1_camera_manager" ],
        [ "ChaseCamera", "class_aerodynamic_objects_1_1_demos_1_1_chase_camera.html", "class_aerodynamic_objects_1_1_demos_1_1_chase_camera" ],
        [ "ConfigurableModelGliderEditor", "class_aerodynamic_objects_1_1_demos_1_1_configurable_model_glider_editor.html", "class_aerodynamic_objects_1_1_demos_1_1_configurable_model_glider_editor" ],
        [ "ContiguousLineVortexSpawner", "class_aerodynamic_objects_1_1_demos_1_1_contiguous_line_vortex_spawner.html", "class_aerodynamic_objects_1_1_demos_1_1_contiguous_line_vortex_spawner" ],
        [ "ControllableModelGlider", "class_aerodynamic_objects_1_1_demos_1_1_controllable_model_glider.html", "class_aerodynamic_objects_1_1_demos_1_1_controllable_model_glider" ],
        [ "CupAnemometer", "class_aerodynamic_objects_1_1_demos_1_1_cup_anemometer.html", "class_aerodynamic_objects_1_1_demos_1_1_cup_anemometer" ],
        [ "ExampleSpawner", "class_aerodynamic_objects_1_1_demos_1_1_example_spawner.html", "class_aerodynamic_objects_1_1_demos_1_1_example_spawner" ],
        [ "FanController", "class_aerodynamic_objects_1_1_demos_1_1_fan_controller.html", "class_aerodynamic_objects_1_1_demos_1_1_fan_controller" ],
        [ "FanFlowField", "class_aerodynamic_objects_1_1_demos_1_1_fan_flow_field.html", "class_aerodynamic_objects_1_1_demos_1_1_fan_flow_field" ],
        [ "FixedOrbitCamera", "class_aerodynamic_objects_1_1_demos_1_1_fixed_orbit_camera.html", "class_aerodynamic_objects_1_1_demos_1_1_fixed_orbit_camera" ],
        [ "FlightInfoDisplay", "class_aerodynamic_objects_1_1_demos_1_1_flight_info_display.html", "class_aerodynamic_objects_1_1_demos_1_1_flight_info_display" ],
        [ "FlowRoundAnAerofoil", "class_aerodynamic_objects_1_1_demos_1_1_flow_round_an_aerofoil.html", "class_aerodynamic_objects_1_1_demos_1_1_flow_round_an_aerofoil" ],
        [ "FluidMotionDriver", "class_aerodynamic_objects_1_1_demos_1_1_fluid_motion_driver.html", "class_aerodynamic_objects_1_1_demos_1_1_fluid_motion_driver" ],
        [ "FreeWheel", "class_aerodynamic_objects_1_1_demos_1_1_free_wheel.html", null ],
        [ "FrisbeeLauncher", "class_aerodynamic_objects_1_1_demos_1_1_frisbee_launcher.html", "class_aerodynamic_objects_1_1_demos_1_1_frisbee_launcher" ],
        [ "Generator", "class_aerodynamic_objects_1_1_demos_1_1_generator.html", "class_aerodynamic_objects_1_1_demos_1_1_generator" ],
        [ "GliderSpawner", "class_aerodynamic_objects_1_1_demos_1_1_glider_spawner.html", "class_aerodynamic_objects_1_1_demos_1_1_glider_spawner" ],
        [ "GliderSpawnerEditor", "class_aerodynamic_objects_1_1_demos_1_1_glider_spawner_editor.html", "class_aerodynamic_objects_1_1_demos_1_1_glider_spawner_editor" ],
        [ "GroundViewCamera", "class_aerodynamic_objects_1_1_demos_1_1_ground_view_camera.html", "class_aerodynamic_objects_1_1_demos_1_1_ground_view_camera" ],
        [ "HangGlider", "class_aerodynamic_objects_1_1_demos_1_1_hang_glider.html", "class_aerodynamic_objects_1_1_demos_1_1_hang_glider" ],
        [ "HangGliderEditor", "class_aerodynamic_objects_1_1_demos_1_1_hang_glider_editor.html", "class_aerodynamic_objects_1_1_demos_1_1_hang_glider_editor" ],
        [ "Helicopter", "class_aerodynamic_objects_1_1_demos_1_1_helicopter.html", "class_aerodynamic_objects_1_1_demos_1_1_helicopter" ],
        [ "HelicopterEditor", "class_aerodynamic_objects_1_1_demos_1_1_helicopter_editor.html", "class_aerodynamic_objects_1_1_demos_1_1_helicopter_editor" ],
        [ "HelicopterRingVortexController", "class_aerodynamic_objects_1_1_demos_1_1_helicopter_ring_vortex_controller.html", "class_aerodynamic_objects_1_1_demos_1_1_helicopter_ring_vortex_controller" ],
        [ "InitialAngularVelocitySetter", "class_aerodynamic_objects_1_1_demos_1_1_initial_angular_velocity_setter.html", "class_aerodynamic_objects_1_1_demos_1_1_initial_angular_velocity_setter" ],
        [ "LiftingFlowAroundACylinder", "class_aerodynamic_objects_1_1_demos_1_1_lifting_flow_around_a_cylinder.html", "class_aerodynamic_objects_1_1_demos_1_1_lifting_flow_around_a_cylinder" ],
        [ "MainRotorController", "class_aerodynamic_objects_1_1_demos_1_1_main_rotor_controller.html", "class_aerodynamic_objects_1_1_demos_1_1_main_rotor_controller" ],
        [ "ModelGlider", "class_aerodynamic_objects_1_1_demos_1_1_model_glider.html", "class_aerodynamic_objects_1_1_demos_1_1_model_glider" ],
        [ "ModelGliderEditor", "class_aerodynamic_objects_1_1_demos_1_1_model_glider_editor.html", "class_aerodynamic_objects_1_1_demos_1_1_model_glider_editor" ],
        [ "OrbitalCamera", "class_aerodynamic_objects_1_1_demos_1_1_orbital_camera.html", "class_aerodynamic_objects_1_1_demos_1_1_orbital_camera" ],
        [ "PaperPlaneFollower", "class_aerodynamic_objects_1_1_demos_1_1_paper_plane_follower.html", "class_aerodynamic_objects_1_1_demos_1_1_paper_plane_follower" ],
        [ "PaperPlaneSpawner", "class_aerodynamic_objects_1_1_demos_1_1_paper_plane_spawner.html", "class_aerodynamic_objects_1_1_demos_1_1_paper_plane_spawner" ],
        [ "PlaneSpawner", "class_aerodynamic_objects_1_1_demos_1_1_plane_spawner.html", "class_aerodynamic_objects_1_1_demos_1_1_plane_spawner" ],
        [ "PointInToWind", "class_aerodynamic_objects_1_1_demos_1_1_point_in_to_wind.html", "class_aerodynamic_objects_1_1_demos_1_1_point_in_to_wind" ],
        [ "PowerDisplayPanel", "class_aerodynamic_objects_1_1_demos_1_1_power_display_panel.html", "class_aerodynamic_objects_1_1_demos_1_1_power_display_panel" ],
        [ "PropellerEngine", "class_aerodynamic_objects_1_1_demos_1_1_propeller_engine.html", "class_aerodynamic_objects_1_1_demos_1_1_propeller_engine" ],
        [ "PropellerEngineEditor", "class_aerodynamic_objects_1_1_demos_1_1_propeller_engine_editor.html", "class_aerodynamic_objects_1_1_demos_1_1_propeller_engine_editor" ],
        [ "Quadcopter", "class_aerodynamic_objects_1_1_demos_1_1_quadcopter.html", "class_aerodynamic_objects_1_1_demos_1_1_quadcopter" ],
        [ "QuadcopterEditor", "class_aerodynamic_objects_1_1_demos_1_1_quadcopter_editor.html", "class_aerodynamic_objects_1_1_demos_1_1_quadcopter_editor" ],
        [ "RingVortexSpawner", "class_aerodynamic_objects_1_1_demos_1_1_ring_vortex_spawner.html", "class_aerodynamic_objects_1_1_demos_1_1_ring_vortex_spawner" ],
        [ "RingVortexTunnelController", "class_aerodynamic_objects_1_1_demos_1_1_ring_vortex_tunnel_controller.html", "class_aerodynamic_objects_1_1_demos_1_1_ring_vortex_tunnel_controller" ],
        [ "SceneReset", "class_aerodynamic_objects_1_1_demos_1_1_scene_reset.html", "class_aerodynamic_objects_1_1_demos_1_1_scene_reset" ],
        [ "SizeController", "class_aerodynamic_objects_1_1_demos_1_1_size_controller.html", "class_aerodynamic_objects_1_1_demos_1_1_size_controller" ],
        [ "SourceSpawner", "class_aerodynamic_objects_1_1_demos_1_1_source_spawner.html", "class_aerodynamic_objects_1_1_demos_1_1_source_spawner" ],
        [ "StringForceSensor", "class_aerodynamic_objects_1_1_demos_1_1_string_force_sensor.html", "class_aerodynamic_objects_1_1_demos_1_1_string_force_sensor" ],
        [ "StringRenderer", "class_aerodynamic_objects_1_1_demos_1_1_string_renderer.html", "class_aerodynamic_objects_1_1_demos_1_1_string_renderer" ],
        [ "SurfaceParticles", "class_aerodynamic_objects_1_1_demos_1_1_surface_particles.html", "class_aerodynamic_objects_1_1_demos_1_1_surface_particles" ],
        [ "TailRotorController", "class_aerodynamic_objects_1_1_demos_1_1_tail_rotor_controller.html", "class_aerodynamic_objects_1_1_demos_1_1_tail_rotor_controller" ],
        [ "TimeScaleSetter", "class_aerodynamic_objects_1_1_demos_1_1_time_scale_setter.html", "class_aerodynamic_objects_1_1_demos_1_1_time_scale_setter" ],
        [ "TimeStepSetter", "class_aerodynamic_objects_1_1_demos_1_1_time_step_setter.html", "class_aerodynamic_objects_1_1_demos_1_1_time_step_setter" ],
        [ "TransformRotator", "class_aerodynamic_objects_1_1_demos_1_1_transform_rotator.html", "class_aerodynamic_objects_1_1_demos_1_1_transform_rotator" ],
        [ "TransportAircraft", "class_aerodynamic_objects_1_1_demos_1_1_transport_aircraft.html", "class_aerodynamic_objects_1_1_demos_1_1_transport_aircraft" ],
        [ "TransportAircraftEditor", "class_aerodynamic_objects_1_1_demos_1_1_transport_aircraft_editor.html", "class_aerodynamic_objects_1_1_demos_1_1_transport_aircraft_editor" ],
        [ "WindSock", "class_aerodynamic_objects_1_1_demos_1_1_wind_sock.html", "class_aerodynamic_objects_1_1_demos_1_1_wind_sock" ],
        [ "WindSpeedController", "class_aerodynamic_objects_1_1_demos_1_1_wind_speed_controller.html", "class_aerodynamic_objects_1_1_demos_1_1_wind_speed_controller" ],
        [ "WindTurbineController", "class_aerodynamic_objects_1_1_demos_1_1_wind_turbine_controller.html", "class_aerodynamic_objects_1_1_demos_1_1_wind_turbine_controller" ],
        [ "WindTurbineEditor", "class_aerodynamic_objects_1_1_demos_1_1_wind_turbine_editor.html", "class_aerodynamic_objects_1_1_demos_1_1_wind_turbine_editor" ],
        [ "WindTurbineSceneController", "class_aerodynamic_objects_1_1_demos_1_1_wind_turbine_scene_controller.html", "class_aerodynamic_objects_1_1_demos_1_1_wind_turbine_scene_controller" ],
        [ "WrightFlyer", "class_aerodynamic_objects_1_1_demos_1_1_wright_flyer.html", "class_aerodynamic_objects_1_1_demos_1_1_wright_flyer" ],
        [ "WrightFlyerEditor", "class_aerodynamic_objects_1_1_demos_1_1_wright_flyer_editor.html", "class_aerodynamic_objects_1_1_demos_1_1_wright_flyer_editor" ]
      ] ],
      [ "Flow", "namespace_aerodynamic_objects_1_1_flow.html", [
        [ "AreaSource", "class_aerodynamic_objects_1_1_flow_1_1_area_source.html", "class_aerodynamic_objects_1_1_flow_1_1_area_source" ],
        [ "BluffBodyWake", "class_aerodynamic_objects_1_1_flow_1_1_bluff_body_wake.html", "class_aerodynamic_objects_1_1_flow_1_1_bluff_body_wake" ],
        [ "CreateFlowPrimitiveTools", "class_aerodynamic_objects_1_1_flow_1_1_create_flow_primitive_tools.html", "class_aerodynamic_objects_1_1_flow_1_1_create_flow_primitive_tools" ],
        [ "DisplacementBody", "class_aerodynamic_objects_1_1_flow_1_1_displacement_body.html", "class_aerodynamic_objects_1_1_flow_1_1_displacement_body" ],
        [ "LiftingBodyWake", "class_aerodynamic_objects_1_1_flow_1_1_lifting_body_wake.html", "class_aerodynamic_objects_1_1_flow_1_1_lifting_body_wake" ],
        [ "LineSource", "class_aerodynamic_objects_1_1_flow_1_1_line_source.html", "class_aerodynamic_objects_1_1_flow_1_1_line_source" ],
        [ "PointSource", "class_aerodynamic_objects_1_1_flow_1_1_point_source.html", "class_aerodynamic_objects_1_1_flow_1_1_point_source" ],
        [ "RingVortex", "class_aerodynamic_objects_1_1_flow_1_1_ring_vortex.html", "class_aerodynamic_objects_1_1_flow_1_1_ring_vortex" ],
        [ "RingVortexEditor", "class_aerodynamic_objects_1_1_flow_1_1_ring_vortex_editor.html", "class_aerodynamic_objects_1_1_flow_1_1_ring_vortex_editor" ],
        [ "UniformFlow", "class_aerodynamic_objects_1_1_flow_1_1_uniform_flow.html", "class_aerodynamic_objects_1_1_flow_1_1_uniform_flow" ],
        [ "VortexFilament", "class_aerodynamic_objects_1_1_flow_1_1_vortex_filament.html", "class_aerodynamic_objects_1_1_flow_1_1_vortex_filament" ],
        [ "VortexNode", "class_aerodynamic_objects_1_1_flow_1_1_vortex_node.html", "class_aerodynamic_objects_1_1_flow_1_1_vortex_node" ]
      ] ],
      [ "Tutorials", "namespace_aerodynamic_objects_1_1_tutorials.html", [
        [ "AircraftManager_Tutorial_5", "class_aerodynamic_objects_1_1_tutorials_1_1_aircraft_manager___tutorial__5.html", "class_aerodynamic_objects_1_1_tutorials_1_1_aircraft_manager___tutorial__5" ],
        [ "AircraftManager_Tutorial_6", "class_aerodynamic_objects_1_1_tutorials_1_1_aircraft_manager___tutorial__6.html", "class_aerodynamic_objects_1_1_tutorials_1_1_aircraft_manager___tutorial__6" ],
        [ "AircraftManager_Tutorial_7", "class_aerodynamic_objects_1_1_tutorials_1_1_aircraft_manager___tutorial__7.html", "class_aerodynamic_objects_1_1_tutorials_1_1_aircraft_manager___tutorial__7" ],
        [ "AircraftManager_Tutorial_8", "class_aerodynamic_objects_1_1_tutorials_1_1_aircraft_manager___tutorial__8.html", "class_aerodynamic_objects_1_1_tutorials_1_1_aircraft_manager___tutorial__8" ],
        [ "AircraftManager_Tutorial_9", "class_aerodynamic_objects_1_1_tutorials_1_1_aircraft_manager___tutorial__9.html", "class_aerodynamic_objects_1_1_tutorials_1_1_aircraft_manager___tutorial__9" ]
      ] ],
      [ "Utility", "namespace_aerodynamic_objects_1_1_utility.html", [
        [ "ArrowFader", "class_aerodynamic_objects_1_1_utility_1_1_arrow_fader.html", "class_aerodynamic_objects_1_1_utility_1_1_arrow_fader" ],
        [ "ArrowTileFix", "class_aerodynamic_objects_1_1_utility_1_1_arrow_tile_fix.html", "class_aerodynamic_objects_1_1_utility_1_1_arrow_tile_fix" ],
        [ "FlowPrimitiveLifeTimer", "class_aerodynamic_objects_1_1_utility_1_1_flow_primitive_life_timer.html", "class_aerodynamic_objects_1_1_utility_1_1_flow_primitive_life_timer" ],
        [ "ForceSensor", "class_aerodynamic_objects_1_1_utility_1_1_force_sensor.html", "class_aerodynamic_objects_1_1_utility_1_1_force_sensor" ],
        [ "Gimbal", "class_aerodynamic_objects_1_1_utility_1_1_gimbal.html", "class_aerodynamic_objects_1_1_utility_1_1_gimbal" ],
        [ "GimbalEditor", "class_aerodynamic_objects_1_1_utility_1_1_gimbal_editor.html", "class_aerodynamic_objects_1_1_utility_1_1_gimbal_editor" ],
        [ "GlobalFluidDebugger", "class_aerodynamic_objects_1_1_utility_1_1_global_fluid_debugger.html", "class_aerodynamic_objects_1_1_utility_1_1_global_fluid_debugger" ],
        [ "IgnoreInteractionHelper", "class_aerodynamic_objects_1_1_utility_1_1_ignore_interaction_helper.html", "class_aerodynamic_objects_1_1_utility_1_1_ignore_interaction_helper" ],
        [ "LifeTimer", "class_aerodynamic_objects_1_1_utility_1_1_life_timer.html", "class_aerodynamic_objects_1_1_utility_1_1_life_timer" ],
        [ "ObjectSpawner", "class_aerodynamic_objects_1_1_utility_1_1_object_spawner.html", "class_aerodynamic_objects_1_1_utility_1_1_object_spawner" ]
      ] ],
      [ "AerodynamicLoad", "struct_aerodynamic_objects_1_1_aerodynamic_load.html", "struct_aerodynamic_objects_1_1_aerodynamic_load" ],
      [ "AeroGroup", "class_aerodynamic_objects_1_1_aero_group.html", "class_aerodynamic_objects_1_1_aero_group" ],
      [ "AeroObject", "class_aerodynamic_objects_1_1_aero_object.html", "class_aerodynamic_objects_1_1_aero_object" ],
      [ "AeroObjectEditor", "class_aerodynamic_objects_1_1_aero_object_editor.html", "class_aerodynamic_objects_1_1_aero_object_editor" ],
      [ "ArrowComponent", "class_aerodynamic_objects_1_1_arrow_component.html", "class_aerodynamic_objects_1_1_arrow_component" ],
      [ "ArrowLayerCreation", "class_aerodynamic_objects_1_1_arrow_layer_creation.html", null ],
      [ "BoundingVolume", "class_aerodynamic_objects_1_1_bounding_volume.html", "class_aerodynamic_objects_1_1_bounding_volume" ],
      [ "BoundingVolumeCustomDrawer", "class_aerodynamic_objects_1_1_bounding_volume_custom_drawer.html", "class_aerodynamic_objects_1_1_bounding_volume_custom_drawer" ],
      [ "BuoyancyArrow", "class_aerodynamic_objects_1_1_buoyancy_arrow.html", "class_aerodynamic_objects_1_1_buoyancy_arrow" ],
      [ "ControlSurface", "class_aerodynamic_objects_1_1_control_surface.html", "class_aerodynamic_objects_1_1_control_surface" ],
      [ "ControlSurfaceEditor", "class_aerodynamic_objects_1_1_control_surface_editor.html", "class_aerodynamic_objects_1_1_control_surface_editor" ],
      [ "CreateObjectsTools", "class_aerodynamic_objects_1_1_create_objects_tools.html", "class_aerodynamic_objects_1_1_create_objects_tools" ],
      [ "DirectionalVelocity", "class_aerodynamic_objects_1_1_directional_velocity.html", "class_aerodynamic_objects_1_1_directional_velocity" ],
      [ "DirectionalVelocityDrawer", "class_aerodynamic_objects_1_1_directional_velocity_drawer.html", "class_aerodynamic_objects_1_1_directional_velocity_drawer" ],
      [ "DragArrow", "class_aerodynamic_objects_1_1_drag_arrow.html", "class_aerodynamic_objects_1_1_drag_arrow" ],
      [ "FlowAffected", "class_aerodynamic_objects_1_1_flow_affected.html", "class_aerodynamic_objects_1_1_flow_affected" ],
      [ "FlowFieldArrows", "class_aerodynamic_objects_1_1_flow_field_arrows.html", "class_aerodynamic_objects_1_1_flow_field_arrows" ],
      [ "FlowFieldParticles", "class_aerodynamic_objects_1_1_flow_field_particles.html", "class_aerodynamic_objects_1_1_flow_field_particles" ],
      [ "FlowInteractionManager", "class_aerodynamic_objects_1_1_flow_interaction_manager.html", "class_aerodynamic_objects_1_1_flow_interaction_manager" ],
      [ "FlowParticles", "class_aerodynamic_objects_1_1_flow_particles.html", "class_aerodynamic_objects_1_1_flow_particles" ],
      [ "FlowPointParticles", "class_aerodynamic_objects_1_1_flow_point_particles.html", "class_aerodynamic_objects_1_1_flow_point_particles" ],
      [ "FlowPrimitive", "class_aerodynamic_objects_1_1_flow_primitive.html", "class_aerodynamic_objects_1_1_flow_primitive" ],
      [ "FlowSensor", "class_aerodynamic_objects_1_1_flow_sensor.html", "class_aerodynamic_objects_1_1_flow_sensor" ],
      [ "Fluid", "class_aerodynamic_objects_1_1_fluid.html", "class_aerodynamic_objects_1_1_fluid" ],
      [ "FluidProperties", "class_aerodynamic_objects_1_1_fluid_properties.html", "class_aerodynamic_objects_1_1_fluid_properties" ],
      [ "FluidVolume", "class_aerodynamic_objects_1_1_fluid_volume.html", "class_aerodynamic_objects_1_1_fluid_volume" ],
      [ "GlobalFluid", "class_aerodynamic_objects_1_1_global_fluid.html", "class_aerodynamic_objects_1_1_global_fluid" ],
      [ "GlobalFluidWindow", "class_aerodynamic_objects_1_1_global_fluid_window.html", null ],
      [ "LiftArrow", "class_aerodynamic_objects_1_1_lift_arrow.html", "class_aerodynamic_objects_1_1_lift_arrow" ],
      [ "MoveWithFlow", "class_aerodynamic_objects_1_1_move_with_flow.html", "class_aerodynamic_objects_1_1_move_with_flow" ],
      [ "ParticleGrid", "class_aerodynamic_objects_1_1_particle_grid.html", "class_aerodynamic_objects_1_1_particle_grid" ],
      [ "RotationalLiftArrow", "class_aerodynamic_objects_1_1_rotational_lift_arrow.html", "class_aerodynamic_objects_1_1_rotational_lift_arrow" ],
      [ "SensorRake", "class_aerodynamic_objects_1_1_sensor_rake.html", "class_aerodynamic_objects_1_1_sensor_rake" ],
      [ "SurfaceTrails", "class_aerodynamic_objects_1_1_surface_trails.html", "class_aerodynamic_objects_1_1_surface_trails" ],
      [ "UserDragArrow", "class_aerodynamic_objects_1_1_user_drag_arrow.html", "class_aerodynamic_objects_1_1_user_drag_arrow" ],
      [ "WeightArrow", "class_aerodynamic_objects_1_1_weight_arrow.html", "class_aerodynamic_objects_1_1_weight_arrow" ],
      [ "WindArrow", "class_aerodynamic_objects_1_1_wind_arrow.html", "class_aerodynamic_objects_1_1_wind_arrow" ],
      [ "WindTools", "class_aerodynamic_objects_1_1_wind_tools.html", "class_aerodynamic_objects_1_1_wind_tools" ]
    ] ]
];