var hierarchy =
[
    [ "AerodynamicObjects.AerodynamicLoad", "struct_aerodynamic_objects_1_1_aerodynamic_load.html", null ],
    [ "AerodynamicObjects.ArrowComponent.Arrow", "class_aerodynamic_objects_1_1_arrow_component_1_1_arrow.html", null ],
    [ "AerodynamicObjects.Utility.ArrowFader", "class_aerodynamic_objects_1_1_utility_1_1_arrow_fader.html", null ],
    [ "AerodynamicObjects.ArrowLayerCreation", "class_aerodynamic_objects_1_1_arrow_layer_creation.html", null ],
    [ "AerodynamicObjects.BoundingVolume", "class_aerodynamic_objects_1_1_bounding_volume.html", null ],
    [ "AerodynamicObjects.Flow.CreateFlowPrimitiveTools", "class_aerodynamic_objects_1_1_flow_1_1_create_flow_primitive_tools.html", null ],
    [ "AerodynamicObjects.CreateObjectsTools", "class_aerodynamic_objects_1_1_create_objects_tools.html", null ],
    [ "AerodynamicObjects.Aerodynamics.RotationalDampingModel.DampingAxisModel", "class_aerodynamic_objects_1_1_aerodynamics_1_1_rotational_damping_model_1_1_damping_axis_model.html", null ],
    [ "AerodynamicObjects.DirectionalVelocity", "class_aerodynamic_objects_1_1_directional_velocity.html", null ],
    [ "AerodynamicObjects.Aerodynamics.DragModel.DragModel2D", "class_aerodynamic_objects_1_1_aerodynamics_1_1_drag_model_1_1_drag_model2_d.html", null ],
    [ "Editor", null, [
      [ "AerodynamicObjects.AeroObjectEditor", "class_aerodynamic_objects_1_1_aero_object_editor.html", null ],
      [ "AerodynamicObjects.ControlSurfaceEditor", "class_aerodynamic_objects_1_1_control_surface_editor.html", null ],
      [ "AerodynamicObjects.Demos.AirshipEditor", "class_aerodynamic_objects_1_1_demos_1_1_airship_editor.html", null ],
      [ "AerodynamicObjects.Demos.BalloonControllerEditor", "class_aerodynamic_objects_1_1_demos_1_1_balloon_controller_editor.html", null ],
      [ "AerodynamicObjects.Demos.ConfigurableModelGliderEditor", "class_aerodynamic_objects_1_1_demos_1_1_configurable_model_glider_editor.html", null ],
      [ "AerodynamicObjects.Demos.GliderSpawnerEditor", "class_aerodynamic_objects_1_1_demos_1_1_glider_spawner_editor.html", null ],
      [ "AerodynamicObjects.Demos.HangGliderEditor", "class_aerodynamic_objects_1_1_demos_1_1_hang_glider_editor.html", null ],
      [ "AerodynamicObjects.Demos.HelicopterEditor", "class_aerodynamic_objects_1_1_demos_1_1_helicopter_editor.html", null ],
      [ "AerodynamicObjects.Demos.ModelGliderEditor", "class_aerodynamic_objects_1_1_demos_1_1_model_glider_editor.html", null ],
      [ "AerodynamicObjects.Demos.PropellerEngineEditor", "class_aerodynamic_objects_1_1_demos_1_1_propeller_engine_editor.html", null ],
      [ "AerodynamicObjects.Demos.QuadcopterEditor", "class_aerodynamic_objects_1_1_demos_1_1_quadcopter_editor.html", null ],
      [ "AerodynamicObjects.Demos.TransportAircraftEditor", "class_aerodynamic_objects_1_1_demos_1_1_transport_aircraft_editor.html", null ],
      [ "AerodynamicObjects.Demos.WindTurbineEditor", "class_aerodynamic_objects_1_1_demos_1_1_wind_turbine_editor.html", null ],
      [ "AerodynamicObjects.Demos.WrightFlyerEditor", "class_aerodynamic_objects_1_1_demos_1_1_wright_flyer_editor.html", null ],
      [ "AerodynamicObjects.Flow.RingVortexEditor", "class_aerodynamic_objects_1_1_flow_1_1_ring_vortex_editor.html", null ],
      [ "AerodynamicObjects.Utility.GimbalEditor", "class_aerodynamic_objects_1_1_utility_1_1_gimbal_editor.html", null ]
    ] ],
    [ "EditorWindow", null, [
      [ "AerodynamicObjects.GlobalFluidWindow", "class_aerodynamic_objects_1_1_global_fluid_window.html", null ]
    ] ],
    [ "AerodynamicObjects.FlowInteractionManager", "class_aerodynamic_objects_1_1_flow_interaction_manager.html", null ],
    [ "AerodynamicObjects.Fluid", "class_aerodynamic_objects_1_1_fluid.html", null ],
    [ "AerodynamicObjects.GlobalFluid", "class_aerodynamic_objects_1_1_global_fluid.html", null ],
    [ "AerodynamicObjects.Aerodynamics.IAerodynamicModel", "interface_aerodynamic_objects_1_1_aerodynamics_1_1_i_aerodynamic_model.html", [
      [ "AerodynamicObjects.Aerodynamics.AdvancedBuoyancyModel", "class_aerodynamic_objects_1_1_aerodynamics_1_1_advanced_buoyancy_model.html", null ],
      [ "AerodynamicObjects.Aerodynamics.BuoyancyModel", "class_aerodynamic_objects_1_1_aerodynamics_1_1_buoyancy_model.html", null ],
      [ "AerodynamicObjects.Aerodynamics.DragModel", "class_aerodynamic_objects_1_1_aerodynamics_1_1_drag_model.html", null ],
      [ "AerodynamicObjects.Aerodynamics.LiftModel", "class_aerodynamic_objects_1_1_aerodynamics_1_1_lift_model.html", null ],
      [ "AerodynamicObjects.Aerodynamics.RotationalDampingModel", "class_aerodynamic_objects_1_1_aerodynamics_1_1_rotational_damping_model.html", null ],
      [ "AerodynamicObjects.Aerodynamics.RotationalLiftModel", "class_aerodynamic_objects_1_1_aerodynamics_1_1_rotational_lift_model.html", null ],
      [ "AerodynamicObjects.Aerodynamics.UserSuppliedDragModel", "class_aerodynamic_objects_1_1_aerodynamics_1_1_user_supplied_drag_model.html", null ]
    ] ],
    [ "AerodynamicObjects.Utility.IgnoreInteractionHelper.IgnoreInteractionCollection", "class_aerodynamic_objects_1_1_utility_1_1_ignore_interaction_helper_1_1_ignore_interaction_collection.html", null ],
    [ "MonoBehaviour", null, [
      [ "AerodynamicObjects.AeroGroup", "class_aerodynamic_objects_1_1_aero_group.html", null ],
      [ "AerodynamicObjects.Aerodynamics.AdvancedBuoyancyModel", "class_aerodynamic_objects_1_1_aerodynamics_1_1_advanced_buoyancy_model.html", null ],
      [ "AerodynamicObjects.Aerodynamics.UserSuppliedDragModel", "class_aerodynamic_objects_1_1_aerodynamics_1_1_user_supplied_drag_model.html", null ],
      [ "AerodynamicObjects.ArrowComponent", "class_aerodynamic_objects_1_1_arrow_component.html", [
        [ "AerodynamicObjects.BuoyancyArrow", "class_aerodynamic_objects_1_1_buoyancy_arrow.html", null ],
        [ "AerodynamicObjects.Control.SimpleThrustArrow", "class_aerodynamic_objects_1_1_control_1_1_simple_thrust_arrow.html", null ],
        [ "AerodynamicObjects.DragArrow", "class_aerodynamic_objects_1_1_drag_arrow.html", null ],
        [ "AerodynamicObjects.LiftArrow", "class_aerodynamic_objects_1_1_lift_arrow.html", null ],
        [ "AerodynamicObjects.RotationalLiftArrow", "class_aerodynamic_objects_1_1_rotational_lift_arrow.html", null ],
        [ "AerodynamicObjects.UserDragArrow", "class_aerodynamic_objects_1_1_user_drag_arrow.html", null ],
        [ "AerodynamicObjects.WeightArrow", "class_aerodynamic_objects_1_1_weight_arrow.html", null ],
        [ "AerodynamicObjects.WindArrow", "class_aerodynamic_objects_1_1_wind_arrow.html", null ]
      ] ],
      [ "AerodynamicObjects.Control.Actuator", "class_aerodynamic_objects_1_1_control_1_1_actuator.html", [
        [ "AerodynamicObjects.Control.SimpleThruster", "class_aerodynamic_objects_1_1_control_1_1_simple_thruster.html", null ]
      ] ],
      [ "AerodynamicObjects.ControlSurface", "class_aerodynamic_objects_1_1_control_surface.html", null ],
      [ "AerodynamicObjects.Demos.AeroObjectSpawner", "class_aerodynamic_objects_1_1_demos_1_1_aero_object_spawner.html", null ],
      [ "AerodynamicObjects.Demos.AlignWithFlow", "class_aerodynamic_objects_1_1_demos_1_1_align_with_flow.html", null ],
      [ "AerodynamicObjects.Demos.AnemometerSpeedLogger", "class_aerodynamic_objects_1_1_demos_1_1_anemometer_speed_logger.html", null ],
      [ "AerodynamicObjects.Demos.AngularVelocityWarning", "class_aerodynamic_objects_1_1_demos_1_1_angular_velocity_warning.html", null ],
      [ "AerodynamicObjects.Demos.BalloonController", "class_aerodynamic_objects_1_1_demos_1_1_balloon_controller.html", null ],
      [ "AerodynamicObjects.Demos.BalloonString", "class_aerodynamic_objects_1_1_demos_1_1_balloon_string.html", null ],
      [ "AerodynamicObjects.Demos.BaseAircraftController", "class_aerodynamic_objects_1_1_demos_1_1_base_aircraft_controller.html", [
        [ "AerodynamicObjects.Demos.Airship", "class_aerodynamic_objects_1_1_demos_1_1_airship.html", null ],
        [ "AerodynamicObjects.Demos.ControllableModelGlider", "class_aerodynamic_objects_1_1_demos_1_1_controllable_model_glider.html", null ],
        [ "AerodynamicObjects.Demos.HangGlider", "class_aerodynamic_objects_1_1_demos_1_1_hang_glider.html", null ],
        [ "AerodynamicObjects.Demos.Helicopter", "class_aerodynamic_objects_1_1_demos_1_1_helicopter.html", null ],
        [ "AerodynamicObjects.Demos.Quadcopter", "class_aerodynamic_objects_1_1_demos_1_1_quadcopter.html", null ],
        [ "AerodynamicObjects.Demos.TransportAircraft", "class_aerodynamic_objects_1_1_demos_1_1_transport_aircraft.html", null ],
        [ "AerodynamicObjects.Demos.WrightFlyer", "class_aerodynamic_objects_1_1_demos_1_1_wright_flyer.html", null ]
      ] ],
      [ "AerodynamicObjects.Demos.BodyMotion", "class_aerodynamic_objects_1_1_demos_1_1_body_motion.html", null ],
      [ "AerodynamicObjects.Demos.CameraBillboard", "class_aerodynamic_objects_1_1_demos_1_1_camera_billboard.html", null ],
      [ "AerodynamicObjects.Demos.CameraManager", "class_aerodynamic_objects_1_1_demos_1_1_camera_manager.html", null ],
      [ "AerodynamicObjects.Demos.ChaseCamera", "class_aerodynamic_objects_1_1_demos_1_1_chase_camera.html", null ],
      [ "AerodynamicObjects.Demos.CupAnemometer", "class_aerodynamic_objects_1_1_demos_1_1_cup_anemometer.html", null ],
      [ "AerodynamicObjects.Demos.FanController", "class_aerodynamic_objects_1_1_demos_1_1_fan_controller.html", null ],
      [ "AerodynamicObjects.Demos.FanFlowField", "class_aerodynamic_objects_1_1_demos_1_1_fan_flow_field.html", null ],
      [ "AerodynamicObjects.Demos.FixedOrbitCamera", "class_aerodynamic_objects_1_1_demos_1_1_fixed_orbit_camera.html", null ],
      [ "AerodynamicObjects.Demos.FlightInfoDisplay", "class_aerodynamic_objects_1_1_demos_1_1_flight_info_display.html", null ],
      [ "AerodynamicObjects.Demos.FluidMotionDriver", "class_aerodynamic_objects_1_1_demos_1_1_fluid_motion_driver.html", null ],
      [ "AerodynamicObjects.Demos.FreeWheel", "class_aerodynamic_objects_1_1_demos_1_1_free_wheel.html", null ],
      [ "AerodynamicObjects.Demos.Generator", "class_aerodynamic_objects_1_1_demos_1_1_generator.html", null ],
      [ "AerodynamicObjects.Demos.GliderSpawner", "class_aerodynamic_objects_1_1_demos_1_1_glider_spawner.html", null ],
      [ "AerodynamicObjects.Demos.GroundViewCamera", "class_aerodynamic_objects_1_1_demos_1_1_ground_view_camera.html", null ],
      [ "AerodynamicObjects.Demos.HelicopterRingVortexController", "class_aerodynamic_objects_1_1_demos_1_1_helicopter_ring_vortex_controller.html", null ],
      [ "AerodynamicObjects.Demos.InitialAngularVelocitySetter", "class_aerodynamic_objects_1_1_demos_1_1_initial_angular_velocity_setter.html", null ],
      [ "AerodynamicObjects.Demos.MainRotorController", "class_aerodynamic_objects_1_1_demos_1_1_main_rotor_controller.html", null ],
      [ "AerodynamicObjects.Demos.ModelGlider", "class_aerodynamic_objects_1_1_demos_1_1_model_glider.html", null ],
      [ "AerodynamicObjects.Demos.OrbitalCamera", "class_aerodynamic_objects_1_1_demos_1_1_orbital_camera.html", null ],
      [ "AerodynamicObjects.Demos.PaperPlaneFollower", "class_aerodynamic_objects_1_1_demos_1_1_paper_plane_follower.html", null ],
      [ "AerodynamicObjects.Demos.PlaneSpawner", "class_aerodynamic_objects_1_1_demos_1_1_plane_spawner.html", null ],
      [ "AerodynamicObjects.Demos.PointInToWind", "class_aerodynamic_objects_1_1_demos_1_1_point_in_to_wind.html", null ],
      [ "AerodynamicObjects.Demos.PowerDisplayPanel", "class_aerodynamic_objects_1_1_demos_1_1_power_display_panel.html", null ],
      [ "AerodynamicObjects.Demos.PropellerEngine", "class_aerodynamic_objects_1_1_demos_1_1_propeller_engine.html", null ],
      [ "AerodynamicObjects.Demos.RingVortexTunnelController", "class_aerodynamic_objects_1_1_demos_1_1_ring_vortex_tunnel_controller.html", null ],
      [ "AerodynamicObjects.Demos.SceneReset", "class_aerodynamic_objects_1_1_demos_1_1_scene_reset.html", null ],
      [ "AerodynamicObjects.Demos.SizeController", "class_aerodynamic_objects_1_1_demos_1_1_size_controller.html", null ],
      [ "AerodynamicObjects.Demos.StringForceSensor", "class_aerodynamic_objects_1_1_demos_1_1_string_force_sensor.html", null ],
      [ "AerodynamicObjects.Demos.StringRenderer", "class_aerodynamic_objects_1_1_demos_1_1_string_renderer.html", null ],
      [ "AerodynamicObjects.Demos.TailRotorController", "class_aerodynamic_objects_1_1_demos_1_1_tail_rotor_controller.html", null ],
      [ "AerodynamicObjects.Demos.TimeScaleSetter", "class_aerodynamic_objects_1_1_demos_1_1_time_scale_setter.html", null ],
      [ "AerodynamicObjects.Demos.TimeStepSetter", "class_aerodynamic_objects_1_1_demos_1_1_time_step_setter.html", null ],
      [ "AerodynamicObjects.Demos.TransformRotator", "class_aerodynamic_objects_1_1_demos_1_1_transform_rotator.html", null ],
      [ "AerodynamicObjects.Demos.WindSock", "class_aerodynamic_objects_1_1_demos_1_1_wind_sock.html", null ],
      [ "AerodynamicObjects.Demos.WindSpeedController", "class_aerodynamic_objects_1_1_demos_1_1_wind_speed_controller.html", null ],
      [ "AerodynamicObjects.Demos.WindTurbineController", "class_aerodynamic_objects_1_1_demos_1_1_wind_turbine_controller.html", null ],
      [ "AerodynamicObjects.Demos.WindTurbineSceneController", "class_aerodynamic_objects_1_1_demos_1_1_wind_turbine_scene_controller.html", null ],
      [ "AerodynamicObjects.Flow.BluffBodyWake", "class_aerodynamic_objects_1_1_flow_1_1_bluff_body_wake.html", null ],
      [ "AerodynamicObjects.Flow.LiftingBodyWake", "class_aerodynamic_objects_1_1_flow_1_1_lifting_body_wake.html", null ],
      [ "AerodynamicObjects.Flow.RingVortex", "class_aerodynamic_objects_1_1_flow_1_1_ring_vortex.html", null ],
      [ "AerodynamicObjects.Flow.VortexNode", "class_aerodynamic_objects_1_1_flow_1_1_vortex_node.html", null ],
      [ "AerodynamicObjects.FlowAffected", "class_aerodynamic_objects_1_1_flow_affected.html", [
        [ "AerodynamicObjects.FlowFieldArrows", "class_aerodynamic_objects_1_1_flow_field_arrows.html", null ],
        [ "AerodynamicObjects.FlowParticles", "class_aerodynamic_objects_1_1_flow_particles.html", [
          [ "AerodynamicObjects.Demos.SurfaceParticles", "class_aerodynamic_objects_1_1_demos_1_1_surface_particles.html", null ],
          [ "AerodynamicObjects.FlowFieldParticles", "class_aerodynamic_objects_1_1_flow_field_particles.html", null ],
          [ "AerodynamicObjects.FlowPointParticles", "class_aerodynamic_objects_1_1_flow_point_particles.html", null ],
          [ "AerodynamicObjects.ParticleGrid", "class_aerodynamic_objects_1_1_particle_grid.html", null ],
          [ "AerodynamicObjects.SurfaceTrails", "class_aerodynamic_objects_1_1_surface_trails.html", null ]
        ] ],
        [ "AerodynamicObjects.FlowSensor", "class_aerodynamic_objects_1_1_flow_sensor.html", [
          [ "AerodynamicObjects.AeroObject", "class_aerodynamic_objects_1_1_aero_object.html", null ]
        ] ],
        [ "AerodynamicObjects.MoveWithFlow", "class_aerodynamic_objects_1_1_move_with_flow.html", null ],
        [ "AerodynamicObjects.SensorRake", "class_aerodynamic_objects_1_1_sensor_rake.html", null ]
      ] ],
      [ "AerodynamicObjects.FlowPrimitive", "class_aerodynamic_objects_1_1_flow_primitive.html", [
        [ "AerodynamicObjects.Demos.FlowRoundAnAerofoil", "class_aerodynamic_objects_1_1_demos_1_1_flow_round_an_aerofoil.html", null ],
        [ "AerodynamicObjects.Demos.LiftingFlowAroundACylinder", "class_aerodynamic_objects_1_1_demos_1_1_lifting_flow_around_a_cylinder.html", null ],
        [ "AerodynamicObjects.Flow.AreaSource", "class_aerodynamic_objects_1_1_flow_1_1_area_source.html", null ],
        [ "AerodynamicObjects.Flow.DisplacementBody", "class_aerodynamic_objects_1_1_flow_1_1_displacement_body.html", null ],
        [ "AerodynamicObjects.Flow.LineSource", "class_aerodynamic_objects_1_1_flow_1_1_line_source.html", null ],
        [ "AerodynamicObjects.Flow.PointSource", "class_aerodynamic_objects_1_1_flow_1_1_point_source.html", null ],
        [ "AerodynamicObjects.Flow.UniformFlow", "class_aerodynamic_objects_1_1_flow_1_1_uniform_flow.html", null ],
        [ "AerodynamicObjects.Flow.VortexFilament", "class_aerodynamic_objects_1_1_flow_1_1_vortex_filament.html", null ]
      ] ],
      [ "AerodynamicObjects.FluidVolume", "class_aerodynamic_objects_1_1_fluid_volume.html", null ],
      [ "AerodynamicObjects.Tutorials.AircraftManager_Tutorial_5", "class_aerodynamic_objects_1_1_tutorials_1_1_aircraft_manager___tutorial__5.html", null ],
      [ "AerodynamicObjects.Tutorials.AircraftManager_Tutorial_6", "class_aerodynamic_objects_1_1_tutorials_1_1_aircraft_manager___tutorial__6.html", null ],
      [ "AerodynamicObjects.Tutorials.AircraftManager_Tutorial_7", "class_aerodynamic_objects_1_1_tutorials_1_1_aircraft_manager___tutorial__7.html", null ],
      [ "AerodynamicObjects.Tutorials.AircraftManager_Tutorial_8", "class_aerodynamic_objects_1_1_tutorials_1_1_aircraft_manager___tutorial__8.html", null ],
      [ "AerodynamicObjects.Tutorials.AircraftManager_Tutorial_9", "class_aerodynamic_objects_1_1_tutorials_1_1_aircraft_manager___tutorial__9.html", null ],
      [ "AerodynamicObjects.Utility.ArrowTileFix", "class_aerodynamic_objects_1_1_utility_1_1_arrow_tile_fix.html", null ],
      [ "AerodynamicObjects.Utility.FlowPrimitiveLifeTimer", "class_aerodynamic_objects_1_1_utility_1_1_flow_primitive_life_timer.html", null ],
      [ "AerodynamicObjects.Utility.ForceSensor", "class_aerodynamic_objects_1_1_utility_1_1_force_sensor.html", null ],
      [ "AerodynamicObjects.Utility.Gimbal", "class_aerodynamic_objects_1_1_utility_1_1_gimbal.html", null ],
      [ "AerodynamicObjects.Utility.GlobalFluidDebugger", "class_aerodynamic_objects_1_1_utility_1_1_global_fluid_debugger.html", null ],
      [ "AerodynamicObjects.Utility.IgnoreInteractionHelper", "class_aerodynamic_objects_1_1_utility_1_1_ignore_interaction_helper.html", null ],
      [ "AerodynamicObjects.Utility.LifeTimer", "class_aerodynamic_objects_1_1_utility_1_1_life_timer.html", null ],
      [ "AerodynamicObjects.Utility.ObjectSpawner", "class_aerodynamic_objects_1_1_utility_1_1_object_spawner.html", [
        [ "AerodynamicObjects.Demos.ContiguousLineVortexSpawner", "class_aerodynamic_objects_1_1_demos_1_1_contiguous_line_vortex_spawner.html", null ],
        [ "AerodynamicObjects.Demos.ExampleSpawner", "class_aerodynamic_objects_1_1_demos_1_1_example_spawner.html", null ],
        [ "AerodynamicObjects.Demos.FrisbeeLauncher", "class_aerodynamic_objects_1_1_demos_1_1_frisbee_launcher.html", null ],
        [ "AerodynamicObjects.Demos.PaperPlaneSpawner", "class_aerodynamic_objects_1_1_demos_1_1_paper_plane_spawner.html", null ],
        [ "AerodynamicObjects.Demos.RingVortexSpawner", "class_aerodynamic_objects_1_1_demos_1_1_ring_vortex_spawner.html", null ],
        [ "AerodynamicObjects.Demos.SourceSpawner", "class_aerodynamic_objects_1_1_demos_1_1_source_spawner.html", null ]
      ] ]
    ] ],
    [ "AerodynamicObjects.Control.PIDController", "class_aerodynamic_objects_1_1_control_1_1_p_i_d_controller.html", null ],
    [ "PropertyDrawer", null, [
      [ "AerodynamicObjects.BoundingVolumeCustomDrawer", "class_aerodynamic_objects_1_1_bounding_volume_custom_drawer.html", null ],
      [ "AerodynamicObjects.Control.PIDDrawer", "class_aerodynamic_objects_1_1_control_1_1_p_i_d_drawer.html", null ],
      [ "AerodynamicObjects.DirectionalVelocityDrawer", "class_aerodynamic_objects_1_1_directional_velocity_drawer.html", null ]
    ] ],
    [ "ScriptableObject", null, [
      [ "AerodynamicObjects.FluidProperties", "class_aerodynamic_objects_1_1_fluid_properties.html", null ]
    ] ],
    [ "AerodynamicObjects.WindTools", "class_aerodynamic_objects_1_1_wind_tools.html", null ]
];